version: '3'

services:
  phpMyAdmin:
    container_name: gestionale-pma
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: gestionale
      PMA_PASSWORD: gestionale
    links:
      - mariadb:database
    expose:
      - 80
    labels:
      - "traefik.port=80"
      - 'traefik.backend=phpmyadmin'
      - 'traefik.enable=true'
      - "traefik.frontend.rule=Host:phpmyadmin.tridentescarface.com"
    networks:
      - proxy