version: '2'

services:
  web:
    container_name: gestionale-web
    image: nginx:alpine
    volumes:
      - ../src:/src
      - ../site.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - php
    expose:
      - 80
    labels:
      - "traefik.port=80"
      - 'traefik.backend=api'
      - 'traefik.enable=true'
      - "traefik.frontend.rule=Host:api.tridentescarface.com"
    networks:
      - proxy

  php:
    container_name: gestionale-php
    build:
      context: ./php
    volumes:
      - ../src:/src
    links:
      - mariadb:database
    labels:
      - traefik.enable=false
    networks:
      - proxy

  mariadb:
    container_name: gestionale-mdb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gestionale
      MYSQL_DATABASE: gestionale
      MYSQL_USER: gestionale
      MYSQL_PASSWORD: gestionale
    volumes:
      - database-data:/var/lib/mysql
      - ../sql:/sql
    labels:
      - traefik.enable=false
    networks:
      - proxy
      
  composer:
    container_name: gestionale-cmp
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - ..:/app
  
  traefik:
    image: traefik:alpine
    restart: always
    command: --api
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../traefik.toml:/traefik.toml
      - ../acme.json:/acme.json
    container_name: traefik
    expose:
      - 8080
    labels:
      - "traefik.port=8080"
      - 'traefik.backend=traefik'
      - 'traefik.enable=true'
      - "traefik.frontend.rule=Host:traefik.tridentescarface.com"

volumes:
  database-data:

networks:
  proxy:
    external: true
  internal:
    driver: bridge